spring:
  application:
    name: receipt-analyzer-service
  datasource:
    url: jdbc:mysql://${DOCKER_IP}:3306/receipt-analyzer-service?useSSL=false&serverTimezone=UTC
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${DOCKER_IP}/auth/realms/activiti
          jwk-set-uri: http://${DOCKER_IP}/auth/realms/activiti/protocol/openid-connect/certs

server:
  port: 8090
  servlet:
    context-path: /api

