networks:
  app-network:

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  keycloak:
    image: keycloak/keycloak:26.3
    container_name: keycloak
    restart: always
    depends_on:
      - mysql
    environment:
      KC_DB: mysql
      KC_DB_URL_HOST: mysql
      KC_DB_PORT: 3306
      KC_DB_USERNAME: ${MYSQL_USER}
      KC_DB_PASSWORD: ${MYSQL_PASSWORD}
      KC_DB_DATABASE: ${KEYCLOAK_DB}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_RELATIVE_PATH: /auth
      KC_HOSTNAME_STRICT_HTTP: true
      KC_HTTP_ENABLED: true
      KC_PROXY: EDGE
    command: start-dev
    ports:
      - "8081:8080"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#    command: [nginx-debug, '-g', 'daemon off;']
    depends_on:
      - keycloak
      - receipt-analyzer-service
    networks:
      - app-network

  receipt-analyzer-service:
    build: receipt-analyzer-service
    container_name: receipt-analyzer-service
    ports:
      - "8090:8090"
    environment:
      RECEIPT_ANALYZER_KEYCLOAK_CLIENT_TOKEN: ${RECEIPT_ANALYZER_KEYCLOAK_CLIENT_TOKEN}
      DOCKER_IP: ${DOCKER_IP}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - app-network


volumes:
  mysql_data: