[versions]
spring-boot = "3.5.3"
lombok = "1.18.46"
pdfbox = "2.0.30"
tess4j = "5.4.0"
commons-text = "1.15.0"
mysql-connector-j = "8.4.0"

[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter", version.ref = "spring-boot" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "spring-boot" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "spring-boot" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security", version.ref = "spring-boot" }
spring-boot-starter-oauth2-resource-server = { module = "org.springframework.boot:spring-boot-starter-oauth2-resource-server", version.ref = "spring-boot" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation", version.ref = "spring-boot" }
pdfbox = { module = "org.apache.pdfbox:pdfbox", version.ref = "pdfbox" }
tess4j = { module = "net.sourceforge.tess4j:tess4j", version.ref = "tess4j" }
commons-text = { module = "org.apache.commons:commons-text", version.ref = "commons-text" }
mysql-connector-j = { module = "com.mysql:mysql-connector-j", version.ref = "mysql-connector-j" }
