<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>pl.madzierski.daniel</groupId>
    <artifactId>receipt-analyzer-service-parent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>receipt-analyzer-service-parent</name>

    <properties>
        <java.version>21</java.version>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <lombok.version>1.18.46</lombok.version>
    </properties>

    <packaging>pom</packaging>

    <modules>
        <module>monolith</module>
        <module>adapters</module>
        <module>app</module>
        <module>domain</module>
    </modules>

</project>